"""Barricade feed-derived DNA implementation."""

from .analysis import (
    artifact_profile,
    build_optimizer_frame,
    count_non_overlapping_subseq,
    estimate_artifact_quality,
    family_signature,
    flatten_trace,
    governance_variance,
    infer_specialization,
    library_metrics,
    lineage_entropy,
    mine_macros_from_elites,
    motif_entropy,
    motif_key,
    normalized_entropy,
    optimizer_combinators,
    optimizer_geometry,
    optimizer_token_histogram,
    semantic_family_credit,
    specialization_entropy,
)
from .constants import (
    ARTIFACT_OPS,
    ARTIFACT_TYPES,
    ALL_TOKENS,
    BASE_MACROS,
    CHARTS,
    COOLING_STABILITY_THRESHOLD,
    COOLING_SUCCESS_THRESHOLD,
    EXPLOIT_ENTRY_THRESHOLD,
    EXPLOIT_EXIT_THRESHOLD,
    EXPLOIT_HOLD,
    EXPLOIT_RETENTION_BONUS,
    MOMENTUM_WINDOW,
    PRIMITIVES,
    REGIME_CENTER,
    SEMANTIC_FAMILIES,
    TASKS,
)
from ._operators import (
    build_protected_tokens,
    crossover,
    mutate,
    random_individual,
    random_token,
    specialization_pair_bonus,
)
from .evolution import (
    best_payload,
    choose_parent,
    compute_governed_fitness,
    ecology_round,
    pick_diverse_elites,
    summarize,
    task_score,
)
from .models import (
    ControllerState,
    Individual,
)
from .pipeline import (
    main,
    run_v311,
)
from .tasks import (
    build_patch_skeleton,
    derive_feed_dna_prior,
    derive_task_ecology,
    seed_population_from_prior,
)

__all__ = [
    # analysis
    "artifact_profile",
    "build_optimizer_frame",
    "count_non_overlapping_subseq",
    "estimate_artifact_quality",
    "family_signature",
    "flatten_trace",
    "governance_variance",
    "infer_specialization",
    "library_metrics",
    "lineage_entropy",
    "mine_macros_from_elites",
    "motif_entropy",
    "motif_key",
    "normalized_entropy",
    "optimizer_combinators",
    "optimizer_geometry",
    "optimizer_token_histogram",
    "semantic_family_credit",
    "specialization_entropy",
    # constants
    "ARTIFACT_OPS",
    "ARTIFACT_TYPES",
    "ALL_TOKENS",
    "BASE_MACROS",
    "CHARTS",
    "COOLING_STABILITY_THRESHOLD",
    "COOLING_SUCCESS_THRESHOLD",
    "EXPLOIT_ENTRY_THRESHOLD",
    "EXPLOIT_EXIT_THRESHOLD",
    "EXPLOIT_HOLD",
    "EXPLOIT_RETENTION_BONUS",
    "MOMENTUM_WINDOW",
    "PRIMITIVES",
    "REGIME_CENTER",
    "SEMANTIC_FAMILIES",
    "TASKS",
    # evolution
    "best_payload",
    "build_protected_tokens",
    "choose_parent",
    "compute_governed_fitness",
    "crossover",
    "ecology_round",
    "mutate",
    "pick_diverse_elites",
    "random_individual",
    "random_token",
    "specialization_pair_bonus",
    "summarize",
    "task_score",
    # models
    "ControllerState",
    "Individual",
    # pipeline
    "main",
    "run_v311",
    # tasks
    "build_patch_skeleton",
    "derive_feed_dna_prior",
    "derive_task_ecology",
    "seed_population_from_prior",
]
